/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "uno-red": "#ff5555",
        "uno-blue": "#5555ff",
        "uno-green": "#55aa55",
        "uno-yellow": "#ffaa00",
        "uno-black": "#000000",
        "on-secondary-fixed": "#003076",
        "surface-variant": "#dbdde0",
        "secondary-container": "#c0d1ff",
        "on-primary-fixed-variant": "#5a0f00",
        "tertiary-dim": "#55aa55",
        "surface-container-low": "#f0f1f3",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#9c9d9f",
        "surface-bright": "#f6f6f8",
        "tertiary-container": "#55aa55",
        "on-primary-fixed": "#000000",
        "error-dim": "#ff5555",
        "surface-tint": "#ff5555",
        "on-tertiary-fixed": "#004820",
        "primary-fixed-dim": "#ff5555",
        "surface-container-highest": "#dbdde0",
        "secondary-dim": "#5555ff",
        "tertiary-fixed": "#55aa55",
        "on-surface": "#2d2f31",
        "outline": "#757779",
        "on-tertiary": "#ffffff",
        "tertiary": "#55aa55",
        "surface-dim": "#d2d4d8",
        "primary-container": "#ff5555",
        "surface-container-high": "#e1e2e5",
        "outline-variant": "#acadaf",
        "surface-container": "#e7e8ea",
        "on-secondary-fixed-variant": "#5555ff",
        "error-container": "#ff5555",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#55aa55",
        "on-primary-container": "#490b00",
        "error": "#ff5555",
        "on-surface-variant": "#5a5c5d",
        "tertiary-fixed-dim": "#55aa55",
        "surface": "#f6f6f8",
        "secondary-fixed": "#5555ff",
        "on-error-container": "#570008",
        "primary-fixed": "#ff5555",
        "on-secondary-container": "#5555ff",
        "secondary-fixed-dim": "#5555ff",
        "secondary": "#5555ff",
        "on-secondary": "#ffffff",
        "background": "#f6f6f8",
        "surface-container-lowest": "#ffffff",
        "primary": "#ff5555",
        "inverse-surface": "#0c0e10",
        "primary-dim": "#d44444",
        "on-background": "#2d2f31",
        "on-tertiary-container": "#ffffff",
        "inverse-primary": "#ff5555"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Be Vietnam Pro"],
        "label": ["Plus Jakarta Sans"]
      },
      borderRadius: {"DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px"},
    },
  },
  plugins: [],
}
